galaxy_names = [
    "Andromeda Alpha",
    "Orion Beta",
    "Centaurus Gamma",
    "Sagittarius Delta",
    "Perseus Epsilon",
    "Lyra Zeta",
    "Pegasus Iota",
    "Antares Kappa",
    "Phoenix Lambda",
    "Draco Mu",
    "Leo Nu",
    "Taurus Omicron",
    "Vela Pi",
    "Ursa Rho",
    "Cetus Sigma",
    "Cassiopeia Tau",
    "Eridanus Upsilon",
    "Fornax Phi",
    "Hydra Chi",
    "Lacerta Psi",
    "Pavo Omega",
    "Whirlpool Majoris",
    "Antares Minoris",
    "Andromeda Alpha",
    "Orion Beta",
    "Centaurus Gamma",
    "Sagittarius Delta",
    "Perseus Epsilon",
    "Lyra Zeta",
    "Pegasus Iota",
    "Antares Kappa",
    "Phoenix Lambda",
    "Draco Mu",
    "Leo Nu",
    "Taurus Omicron",
    "Vela Pi",
    "Ursa Rho",
    "Cetus Sigma",
    "Cassiopeia Tau",
    "Eridanus Upsilon",
    "Fornax Phi",
    "Hydra Chi",
    "Lacerta Psi",
    "Pavo Omega",
    "Whirlpool Majoris",
    "Antares Minoris",
    "Xianzhou",
    "Bellabpoge",
    "Katarina 243",
    "Jslb 69",
    "Nighthawks"
]

planet_names = [
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
    "Eris",
    "Ceres",
    "Haumea",
    "Makemake",
    "Sedna",
    "Orcus",
    "Quaoar",
    "Ixion",
    "Varuna",
    "Chiron",
    "Charon",
    "Deimos",
    "Phobos",
    "Ganymede",
    "Callisto",
    "Io",
    "Europa",
    "Titan",
    "Enceladus",
    "Triton",
    "Proteus",
    "Oberon",
    "Miranda",
    "Ariel",
    "Umbriel",
    "Tethys",
    "Dione",
    "Rhea",
    "Iapetus",
    "Hyperion",
    "Janus",
    "Epimetheus",
    "Pandora",
    "Atlas",
    "Prometheus",
    "Pan",
    "Helene",
    "Calypso",
    "Telesto",
    "Nereid",
    "Thalassa",
    "Larissa",
    "Despina",
    "Galatea",
    "Naiad",
    "Proteus",
    "Psamathe",
    "Sao",
    "Laomedeia",
    "Erinome",
    "Carme",
    "Ananke",
    "Lysithea",
    "Himalia",
    "Elara",
    "Pasiphae",
    "Sinope",
    "Kalyke",
    "Megaclite",
    "Iocaste",
    "Harpalyke",
    "Callirrhoe",
    "Aitne",
    "Kore",
    "Herse",
    "Taygete",
    "Chaldene",
    "Autonoe",
    "Eurydome",
    "Pasithee",
    "Kallisto",
    "Mneme",
    "Euporie",
    "Orthosie",
    "Sponde",
    "Kale",
    "Pasiphae",
    "Polycaste",
    "Cyllene",
    "Rhoe",
    "Hermippe",
    "Arche",
    "Kallichore",
    "Hegemone",
    "Aoede",
    "Kallirrhoe",
    "Eurydike",
    "Kore",
    "Herse",
    "Himalia",
    "Kalyke",
    "Iocaste",
    "Erinome",
    "Aitne",
    "Taygete",
    "Chaldene",
    "Autonoe",
    "Eurydome",
    "Thyone",
    "Harpalyke",
    "Kore",
    "Ananke",
    "Mneme",
    "Methone",
    "Pallene",
    "Polydeuces",
    "Daphnis",
    "Albiorix",
    "Bebhionn",
    "Bergelmir",
    "Bestla",
    "Farbauti",
    "Fenrir",
    "Fornjot",
    "Greip",
    "Hati",
    "Hyrrokkin",
    "Jarnsaxa",
    "Kari",
    "Loge",
    "Mundilfari",
    "Narvi",
    "Siarnaq",
    "Skathi",
    "Skoll",
    "Surtur",
    "Thrymr",
    "Ymir",
    "Exoplanet-Alpha",
    "Zephyria",
    "Xenoria",
    "Nebulosa",
    "Aurora Prime",
    "Caelus Minor",
    "Lyridon",
    "Novaris",
    "Seraphina",
    "Astron",
    "Helianthus",
    "Epsilon Eridani Prime",
    "Cassiopeia Major",
    "Denebria",
    "Aquarion",
    "Pandoros",
    "Korinthia",
    "Pulsar-7X",
    "Quintaria",
    "Vindor",
    "Umbra Major",
    "Hesperia",
    "Novalis",
    "Equinox",
    "Astralis",
    "Nirvana",
    "Elysium",
    "Heliopolis",
    "Celestia",
    "Aurelia",
    "Lumina",
    "Sidera",
    "Stellara",
    "Paxara",
    "Vespera",
    "Oblivion",
    "Nemoria",
    "Exoleth",
    "Solitude",
    "Harmonia",
    "Cynosura",
    "Arcadia",
    "Echelon",
    "Proxima Centauri Prime",
    "Tranquilia",
    "Thalassa Minor",
    "Aeloria",
    "Astridora",
    "Rigel VII",
    "Novus Astra",
    "Astra Luna",
    "Pax Novis",
    "Umbra Prime",
    "Vortigaan",
    "Astronova",
    "Heliopolis Major",
    "Nova Luna",
    "Altairon",
    "Eridanus Minor",
    "Caelum",
    "Serenity",
    "Umbria",
    "Aquila Minor",
    "Lyra Major",
    "Delphion",
    "Eridanis Major",
    "Novus Orbis",
    "Orionia",
    "Pandora Major",
    "Eridanis Minor",
    "Nebulon",
    "Aurelia Nova",
    "Olympus",
    "Astra Solara",
    "Helicon",
    "Solariadis",
    "Vindoria",
    "Vesperalis",
    "Astranor",
    "Oceania",
    "Luminarix",
    "Vortex Minor",
    "Nebulosia",
    "Polaris Prime",
    "Celestialis",
    "Ethernia",
    "Iridia",
    "Luna Nova",
    "Pax Luna",
    "Astralos",
    "Caelum Minor",
    "Exo Novis",
    "Selenos",
    "Eclipsar",
    "Solaria",
    "Ombra",
    "Celesticon",
    "Solariana",
    "Phobian",
    "Nemoria Minor",
    "Paxaria",
    "Luminaris",
    "Caelus Major",
    "Vindor Minor",
    "Astranor Minor",
    "Orbitron",
    "Nebula Nova",
    "Thalassar",
    "Aquila Major",
    "Lyra Minor",
    "Eridanus Major",
    "Orbita",
    "Nebula Minor",
    "Altairia",
    "Lunarion",
    "Solstella",
    "Vortex Major",
    "Nebula Major",
    "Stellara Minor",
    "Luminor",
    "Caelus Minoris",
    "Nebula Majoris",
    "Quasaria",
    "Eskarion",
    "Chronos",
    "Mirandia",
    "Exolux",
    "Astronaris",
    "Nexarion",
    "Polonaris",
    "Zyphoria",
    "Veridian",
    "Lithios",
    "Stellarion",
    "Andromedon",
    "Aurorian",
    "Zephyron",
    "Nexorion",
    "Hydronis",
    "Olympion",
    "Ecliptor",
    "Nebulon",
    "Zypherion",
    "Ethereon",
    "Eridanor",
    "Lyridon",
    "Nexulon",
    "Solstoria",
    "Equinoxar",
    "Zypharis",
    "Orionon",
    "Astronaris",
    "Nexis",
    "Polaron",
    "Pandorion",
    "Orbiton",
    "Zephara",
    "Novarion",
    "Andromedon",
    "Olympis",
    "Eclipsar",
    "Zephyron",
    "Eridis",
    "Stellion",
    "Nexarion",
    "Lyranis",
    "Caelus",
    "Solstia",
    "Veraris",
    "Luminos",
    "Polaris",
    "Nexis",
    "Olymparion",
    "Zephyria",
    "Nebularis",
    "Hydronar",
    "Lithion",
    "Astronis",
    "Quasarion",
    "Stellaris",
    "Eskara",
    "Polonar",
    "Ethernar",
    "Zyphoria",
    "Orbitarion",
    "Andromedius",
    "Chronarion",
    "Nexarix",
    "Exolux",
    "Olymparis",
    "Quasaria",
    "Mirandia",
    "Zephyron",
    "Hydronis",
    "Polonaris",
    "Lithios",
    "Stellarion",
    "Andromedon",
    "Aurorian",
    "Ecliptor",
    "Nebulon",
    "Zypherion",
    "Ethereon",
    "Eridanor",
    "Lyridon",
    "Nexulon",
    "Solstoria",
    "Equinoxar",
    "Zypharis",
    "Orionon",
    "Astronaris",
    "Nexis",
    "Polaron",
    "Pandorion",
    "Orbiton",
    "Zephara",
    "Novarion",
    "Andromedon",
    "Olympis",
    "Eclipsar",
    "Zephyron",
    "Eridis",
    "Stellion",
    "Nexarion",
    "Lyranis",
    "Caelus",
    "Solstia",
    "Veraris",
    "Luminos",
    "Polaris",
    "Nexis",
    "Olymparion",
    "Zephyria",
    "Nebularis",
    "Hydronar",
    "Lithion",
    "Astronis",
    "Quasarion",
    "Stellaris",
    "Eskara",
    "Polonar",
    "Ethernar",
    "Zyphoria",
    "Orbitarion",
    "Andromedius",
    "Chronarion",
    "Nexarix",
    "Exolux",
    "Olymparis",
]



